name: Docker

on:
  workflow_call:
    inputs:
      git-ref:
        required: true
        type: string
        description: "The github ref to checkout for building the Docker images."
      image-prefix:
        required: false
        type: string
        default: surrealdb
        description: "The prefix of the Docker image name. i.e. 'surrealdb' for 'surrealdb/surrealdb'."
      tag-prefix:
        required: true
        type: string
        description: "The prefix of the Docker image tag. i.e. 'nightly' for 'surrealdb/surrealdb:nightly-dev' or 'surrealdb/surrealdb:nightly-fdb'."
      build:
        required: false
        type: boolean
        default: true
        description: "Build the Docker images."
      publish:
        required: false
        type: boolean
        default: false
        description: "Publish the Docker images."
      update-latest:
        required: false
        type: boolean
        default: false
        description: "Update the latest tag of the Docker image."
    secrets:
      DOCKER_USER:
        required: false
      DOCKER_PASS:
        required: false

defaults:
  run:
    shell: bash

env:
  MATRIX:
    include:
      ########################################
      # Base images
      ########################################
      # Prod AMD64 image
      - job-name: Base Prod AMD64
        dockerfile: docker/Dockerfile
        build-target: prod
        platform: linux/amd64
        runner: ubuntu-latest-4-cores
      # Prod ARM64 image
      - job-name: Base Prod ARM64
        dockerfile: docker/Dockerfile
        build-target: prod
        platform: linux/arm64
        runner: ["self-hosted", "arm64", "4-cores"]
      # Dev AMD64 image
      - job-name: Base Dev AMD64
        tag-suffix: -dev
        dockerfile: docker/Dockerfile
        build-target: dev
        platform: linux/amd64
        runner: ubuntu-latest-4-cores
      # Dev ARM64 image
      - job-name: Base Dev ARM64
        tag-suffix: -dev
        dockerfile: docker/Dockerfile
        build-target: dev
        platform: linux/arm64
        runner: ["self-hosted", "arm64", "4-cores"]

      ########################################
      # FoundationDB images (FDB client library is only available for amd64)
      ########################################
      # Prod AMD64 image
      - job-name: FDB Prod AMD64
        image-suffix: -fdb
        dockerfile: docker/Dockerfile.fdb
        build-target: prod
        platform: linux/amd64
        runner: ubuntu-latest-4-cores
      # Dev AMD64 image
      - job-name: FDB Dev AMD64
        image-suffix: -fdb
        tag-suffix: -dev
        dockerfile: docker/Dockerfile.fdb
        build-target: dev
        platform: linux/amd64
        runner: ubuntu-latest-4-cores

jobs:
  prepare:
    name: Prepare steps
    runs-on: ubuntu-latest
    outputs:
      tag-prefix: ${{ steps.tag-prefix.outputs.tag-prefix }}
    steps:
      - name: Sanitize tag name
        id: tag-prefix
        run: |
          echo "tag-prefix=$(echo '${{ inputs.tag-prefix }}' | sed 's/[^a-zA-Z0-9_.-]/-/g' | tr '[:upper:]' '[:lower:]') >> $GITHUB_OUTPUT
          
  build:
    name: Build ${{ matrix.job-name }}
    runs-on: ${{ matrix.runner }}
    needs: prepare
    if: ${{ inputs.build }}
    env:
      DOCKER_IMAGE_REPO: ${{ inputs.image-prefix }}${{ matrix.image-suffix }} # i.e. surrealdb/...
      DOCKER_IMAGE_TAG: ${{ needs.prepare.outputs.tag-prefix }}${{ matrix.tag-suffix }} # i.e. .../nightly-dev
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(env.MATRIX) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the Docker image
        id: build
        outputs:
          ecr-image: ${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE_REPO }}:${{ env.DOCKER_IMAGE_TAG }}
        run: |
          ECR_IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE_REPO }}:${{ env.DOCKER_IMAGE_TAG }}

          docker buildx build \
            --platform ${{ matrix.platform }} \
            --cache-from type=registry,ref=$ECR_IMAGE \
            --cache-to type=inline \
            --file ${{ matrix.dockerfile }} \
            --target ${{ matrix.build-target }} \
            --tag $ECR_IMAGE \
            .

      # Start the docker image as server and wait until it is ready
      - name: Test the Docker image
        run: |
          docker run --net=host --rm ${{ steps.build.outputs.ecr-image }} start 2>&1 >surreal.log &

          retries=5
          until docker run --net=host --rm ${{ steps.build.outputs.ecr-image }} is-ready; do
            retries=$((retries-1))
            if [[ $retries -eq 0 ]]; then
              echo "###"
              echo "### The container is not ready after 5 seconds!"
              echo "###"
              cat surreal.log
              echo "###"
              echo "### ERROR: The docker image is not valid. Aborting."
              echo "###"
              exit 1
            fi
            sleep 1
          done
      
      - name: Push to CI ECR only so we can use it in other jobs
        run: |
          docker push ${{ steps.build.outputs.ecr-image }}

  push:
    name: Push ${{ matrix.job-name }}
    runs-on: ${{ matrix.runner }}
    needs: prepare
    if: ${{ inputs.publish }}
    env:
      DOCKER_IMAGE_REPO: ${{ inputs.image-prefix }}${{ matrix.image-suffix }} # i.e. surrealdb/...
      DOCKER_IMAGE_TAG_CURRENT: ${{ needs.prepare.outputs.tag-prefix }}${{ matrix.tag-suffix }} # i.e. .../nightly-dev
      DOCKER_IMAGE_TAG_LATEST: latest${{ matrix.tag-suffix }} # i.e. .../latest-dev
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(env.MATRIX) }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configure DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # This second build reuses the cache from the build above
      - name: Push the Docker image
        env:
          ECR_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE_REPO }}:${{ env.DOCKER_IMAGE_TAG_CURRENT }}
          DOCKER_IMAGE_CURRENT: docker.io/surrealdb/${{ env.DOCKER_IMAGE_REPO }}:${{ env.DOCKER_IMAGE_TAG_CURRENT }}
        run: |
          echo docker pull ${{ env.ECR_IMAGE }}
          echo docker tag ${{ env.ECR_IMAGE }} ${{ env.DOCKER_IMAGE_CURRENT }}
          echo docker push ${{ env.DOCKER_IMAGE_CURRENT }}
      
      # Push the prod image as latest if this workflow is meant to update the latest tag
      - name: Push the Docker image with tag 'latest'
        if: ${{ inputs.update-latest }}
        env:
          ECR_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_IMAGE_REPO }}:${{ env.DOCKER_IMAGE_TAG_CURRENT }}
          DOCKER_IMAGE_LATEST: docker.io/surrealdb/${{ env.DOCKER_IMAGE_REPO }}:${{ env.DOCKER_IMAGE_TAG_LATEST }}
        run: |
          echo docker pull ${{ env.ECR_IMAGE }}
          echo docker tag ${{ env.ECR_IMAGE }} ${{ env.DOCKER_IMAGE_LATEST }}
          echo docker push ${{ env.DOCKER_IMAGE_LATEST }}
