name: Version release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        default: false
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

jobs:
  release:
    uses: ./.github/workflows/_release.yml
    with:
      version: ${{ github.ref_name }}
      publish: ${{ github.event.inputs.publish == 'true' || github.event_name == 'push' }}
      docker-update-latest: ${{ github.event.inputs.publish == 'true' || github.event_name == 'push' }}
